apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-apifirst
spec:
  selector:
    matchLabels:
      app: msa-apifirst
  replicas: 1
  template:
    metadata:
      labels:
        app: msa-apifirst
    spec:
      containers:
        - name: msa-apifirst
          image: pasapples/msa-apifirst
          ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: msa-apifirst-service
  labels:
    name: msa-apifirst-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: msa-apifirst
  type: NodePort
