apiVersion: apps/v1
kind: Deployment
metadata:
  name: snyk-person-api
  namespace: apis
  annotations:
    orgs.k8s.snyk.io/v1: ORG_ID_HERE
spec:
  selector:
    matchLabels:
      app: snyk-person-api
  replicas: 1
  template:
    metadata:
      labels:
        app: snyk-person-api
    spec:
      containers:
        - name: snyk-person-api
          image: pasapples/person-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: snyk-person-api-lb
  namespace: apis
  labels:
    name: snyk-person-api-lb
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: snyk-person-api
  type: LoadBalancer
