apiVersion: apps/v1
kind: Deployment
metadata:
  name: snyk-person-api
  annotations:
    orgs.k8s.snyk.io/v1: e31be23e-a59f-476d-b861-f0871a1fc011
spec:
  selector:
    matchLabels:
      app: snyk-person-api
  replicas: 1
  template:
    metadata:
      labels:
        app: snyk-person-api
    spec:
      containers:
        - name: snyk-person-api
          image: pasapples/person-service:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: snyk-person-api-service
  labels:
    name: snyk-person-api-service
spec:
  ports:
    - port: 82
      targetPort: 8080
      protocol: TCP
  selector:
    app: snyk-person-api
  type: NodePort
