apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-jib
spec:
  selector:
    matchLabels:
      app: spring-boot-jib
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-jib
    spec:
      containers:
        - name: spring-boot-jib
          image: pasapples/spring-boot-jib
          ports:
          - containerPort: 8080
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "800Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "750m"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-jib-service
  labels:
    name: spring-boot-jib-service
spec:
  ports:
    - port: 81
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-boot-jib
  type: NodePort
